version: '3.1'
services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db:db
  db:
    image: postgres:13.3
    container_name: db
    environment :
      POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: always
    volumes:
      - ./infra/init.sh:/docker-entrypoint-initdb.d/init.sh
