CREATE TABLE application_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(255),
   last_name VARCHAR(255),
   email VARCHAR(255),
   date_of_birth date,
   CONSTRAINT pk_applicationuser PRIMARY KEY (id)
);

ALTER TABLE application_user ADD CONSTRAINT uc_applicationuser_email UNIQUE (email);