CREATE TABLE roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(20),
   CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_roles (
  role_id INTEGER NOT NULL,
   user_id BIGINT NOT NULL,
   CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

ALTER TABLE application_user ADD password VARCHAR(255);

ALTER TABLE user_roles ADD CONSTRAINT fk_userol_on_application_user FOREIGN KEY (user_id) REFERENCES application_user (id);

ALTER TABLE user_roles ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');